language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.2.gemfile
matrix:
  allow_failures:
    - rvm: 2.4.0
    - rvm: ruby-head
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.2.gemfile
script:
  - bundle exec rake rubocop
  - bundle exec rspec
