language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
matrix:
  allow_failures:
    - rvm: 2.4.3
    - rvm: ruby-head
  exclude:
      gemfile: gemfiles/rails_5.0.gemfile
      gemfile: gemfiles/rails_5.1.gemfile
      gemfile: gemfiles/rails_5.2.gemfile
script:
  - bundle exec rake rubocop
  - bundle exec rspec
